alias C='cp --recursive'
alias D='mkdir'
alias F='touch'
alias K='pkill -f'
alias Kd='pkill -f discord'
alias Kf='pkill -f firefox'
alias Kr='pkill -f rocket'
alias Kt='pkill -f thunderbird'
alias L='ls --almost-all --color=auto --classify'
alias M='sudo make clean install'
alias N='nmcli'
alias P='sudo pacman'
alias R!='reboot'
alias R='rm --recursive'
alias Rf='rm --recursive --force'
alias S!='shutdown now'
alias X='startx'
alias Y='yay'
alias YS='yay && shutdown now'
alias a='alsamixer'
alias b='black'
alias c='xclip -selection clipboard'
alias f='firefox-developer-edition'
alias g='git'
alias gA='git add --all && git status --short'
alias gC='git config'
alias gCe='git config user.email'
alias gCeDZ='git config user.email damian.zamola.zamolski@gmail.com'
alias gL='git log'
alias gP='git push'
alias gR='git remote'
alias gRa='git remote add'
alias gRao='git remote add origin'
alias gRv='git remote --verbose'
alias gS='git status'
alias gb='git branch'
alias gbD='git branch --delete --force'
alias gbc='git branch --show-current'
alias gbd='git branch --delete'
alias gc='git commit'
alias gch.='git checkout .'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gchd='git checkout develop'
alias gchm='git checkout master'
alias gcl='git clone'
alias gd='git diff HEAD'
alias gf='git fetch'
alias gi='git init'
alias gid='git init && git config user.email damian.zamola.zamolski@gmail.com'
alias gl='git log --oneline'
alias gm='git merge'
alias gp='git pull'
alias gpo='git pull origin'
alias gpod='git pull origin develop'
alias gpu='git pull upstream'
alias gr='git reset'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gs='git status --short'
alias gw='git worktree'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwm='git worktree move'
alias gwp='git worktree prune'
alias l.='ls --color=auto --classify --directory .*'
alias l='ls --color=auto --classify'
alias ll='ls --color=auto --classify -l'
alias ls='ls --color=auto --classify'
alias m='mvn'
alias mc='mvn clean'
alias mcc='mvn clean compile -Dmaven.test.skip=true -T1C'
alias mci='mvn clean install -Dmaven.test.skip=true -T1C'
alias mciq='mvn clean install -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=postgresql'
alias mciqo='mvn clean install -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=oracle'
alias mcp='mvn clean package -Dmaven.test.skip=true -T1C'
alias mcpq='mvn clean package -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=postgresql'
alias mcpqo='mvn clean package -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=oracle'
alias mct='mvn clean test -T1C'
alias mcv='mvn clean verify -Dmaven.test.skip=true -T1C'
alias mi='mvn install -Dmaven.test.skip=true -T1C'
alias miq='mvn install -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=postgresql'
alias mp='mvn package -Dmaven.test.skip=true -T1C'
alias mpq='mvn package -Dmaven.test.skip=true -T1C -Pcloud -Dquarkus.profile=postgresql'
alias mqc='mvn quarkus:dev -pl chat-im-core -Pcloud -Dquarkus.profile=postgresql -Ddebug=5001'
alias mqi='mvn quarkus:dev -pl info-management-core -Pcloud -Dquarkus.profile=postgresql -Ddebug=5001'
alias mqiv='mvn quarkus:dev -pl info-management-view -Pcloud -Ddebug=5000'
alias mqs='mvn quarkus:dev -pl service-desk-core -Pcloud -Dquarkus.profile=dev -DnoDeps -Ddebug=6001'
alias mqsv='mvn quarkus:dev -pl service-desk-view -Pcloud -Ddebug=6000'
alias n='npm'
alias nI='npm init'
alias nIy='npm init --yes'
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install --global'
alias npw='npx prettier --write'
alias nr='npm run'
alias nrb='npm run build'
alias nrc='npm run cypress'
alias nrd='npm run dev'
alias nrds='npm run dev --workspace server'
alias nrdw='npm run dev --workspace web'
alias nre='npm run export'
alias nrf='npm run format'
alias nrl='npm run lint'
alias nrt='npm run test'
alias p='python'
alias pi='pip install'
alias t='st & disown'
alias u='unzip'
alias v.='nvim .'
alias v='nvim'
alias y='yarn'
alias yr='yarn run'
alias yrc='yarn run clean'
alias yrd='yarn run dev'
alias yrf='yarn run format'
alias yrp='yarn run pull'
alias yrr='yarn run release'
alias yrs='yarn run setup'
alias yrt='yarn run test'
alias yrtc='yarn run test-changed'
alias yrwt='yarn run watch-tests'
alias yyrd='yarn && yarn run dev'
alias yyrr='yarn && yarn run release'
alias z='zip -r'
ga() { git add $1 && git status --short }
pdf() { pandoc $1 --output $1.pdf }
