alias a='alsamixer'
alias b='black'
alias C='cp --recursive'
alias c='xclip -selection clipboard'
alias D='mkdir'
alias dt="date +'%Y-%m-%d %H:%M:%S'"
alias f='firefox-developer-edition'
alias F='touch'
alias g='git'
alias gA='git add --all && git status --short'
alias gb='git branch'
alias gbc='git branch --show-current'
alias gbD='git branch --delete --force'
alias gbd='git branch --delete'
alias gc='git commit'
alias gC='git config'
alias gCe='git config user.email'
alias gCeDZ='git config user.email damian.zamola.zamolski@gmail.com'
alias gch.='git checkout .'
alias gch='git checkout'
alias gchb='git checkout -b'
alias gchd='git checkout development'
alias gcl='git clone'
alias gd='git diff HEAD'
alias gf='git fetch'
alias gi='git init'
alias gid='git init && git config user.email damian.zamola.zamolski@gmail.com'
alias gl='git log --oneline'
alias gL='git log'
alias gm='git merge'
alias gp='git pull'
alias gP='git push'
alias gpo='git pull origin'
alias gpod='git pull origin develop'
alias gpu='git pull upstream'
alias gR='git remote'
alias gRa='git remote add'
alias gRao='git remote add origin'
alias grep='grep --color=auto'
alias grh='git reset HEAD'
alias gRv='git remote --verbose'
alias gs='git status --short 2> /dev/null || for repo in **/.git; do repo=$(dirname $repo); echo -e $bold_blue$repo $bold_green$(git -C $repo branch --show-current)$default_color; git -C $repo status --short; done'
alias gw='git worktree'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwm='git worktree move'
alias gwp='git worktree prune'
alias K='pkill -f'
alias Kd='pkill -f discord'
alias Kf='pkill -f firefox'
alias Kr='pkill -f rocket'
alias Kt='pkill -f thunderbird'
alias l.='ls -1 --color=auto --classify --directory .*'
alias L='ls -1 --almost-all --color=auto --classify'
alias l='ls -1 --color=auto --classify'
alias Ll='ls -1 --almost-all --color=auto --classify -l --human-readable'
alias ll='ls -1 --color=auto --classify -l --human-readable'
alias ls='ls -1 --color=auto --classify'
alias m='make'
alias N='nmcli'
alias n='npm'
alias nI='npm init'
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install --global'
alias nIy='npm init --yes'
alias npw='npx prettier --write'
alias nr='npm run'
alias nrb='npm run build'
alias nrc='npm run cypress'
alias nrd='npm run dev'
alias nrds='npm run dev --workspace server'
alias nrdw='npm run dev --workspace web'
alias nre='npm run export'
alias nrf='npm run format'
alias nrl='npm run lint'
alias nrt='npm run test'
alias p='python'
alias pi='pip install'
alias R!='reboot'
alias R='rm --recursive'
alias RF='rm --recursive --force'
alias S!='shutdown now'
alias t='tree -C'
alias u='unzip'
alias v.='nvim .'
alias v='nvim'
alias X='startx'
alias y='yarn'
alias Y='yay'
alias yr='yarn run'
alias yrc='yarn run clean'
alias yrd='yarn run dev'
alias yrf='yarn run format'
alias yrp='yarn run pull'
alias yrr='yarn run release'
alias yrs='yarn run setup'
alias yrt='yarn run test'
alias yrtc='yarn run test-changed'
alias yrwt='yarn run watch-tests'
alias YS!='yay && shutdown now'
alias yyrd='yarn && yarn run dev'
alias yyrr='yarn && yarn run release'
alias z='zip -r'
ga() { git add $1 && git status --short; }
gr() { git reset $1 && git status --short; }
pdf() { pandoc $1 --output $1.pdf; }
